### ISSUE TITLE
Code/process to host website

### ISSUE THREAD

**Issue by sophia-wright-blue** [dvgodoy/heatingplanet#1]
thank you so much for publishing the website @dvgodoy !

It'd be very helpful to those of us completely unfamiliar with hosting websites if you could share the code/process to host the website and keep it running, thank you

**Comment by dvgodoy** [comment]
Hi @sophia-wright-blue,

The website itself was generated using Quarto to render HTML pages out of Jupyter Notebooks (https://quarto.org/docs/get-started/hello/jupyter.html).

Once the static website was generated by Quarto, I created this repository to host it on GitHub pages (https://pages.github.com/). You can see all the files (HTML, CSS, etc) are inside the `/docs` folder.

Finally, I configured a custom domain for it (https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site).

These steps should suffice for any static website. In my case, the trickiest part was the interactive plot that was built using plotly. The animation over 120 years generated a massive HTML that would take forever to load, so I had to code a lot of Javascript manually to optimize it, and save data in a custom binary file (the `.dat` files) inside `/docs/assets/data` folder.

Hope it helps.

**Comment by sophia-wright-blue** [comment]
thanks so much for the detailed response - this was exactly what I was looking for - looking forward to more blogs/research from you :)
